function [data, truth] = obfuscate(input)
    data = struct('init', input.init, 't', input.t, 'T', input.T, ...
                  'varying', input.varying, 'observed', input.observed, ...
                  'N', input.N, 'traces', input.traces(:, input.observed, :));

    truth = struct('b', input.b, 'D', input.D, 'beta', input.beta, ...
                   't', input.t, 'T', input.T, 'N', input.N, ...
                   'moriginal', input.moriginal, 'mdoriginal', input.mdoriginal, ...
                   'original', input.original, 'doriginal', input.doriginal);
end
    